image: node:16

definitions: 
  steps: 
    - step: &deploy-to-production
        name: Deploy to production
        deployment: Production
        trigger: manual
        clone:
          enabled: false
        script:
          # sync your files to S3
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $CF_SITE_BUCKET
              LOCAL_PATH: 'build'
          # triggering a distribution invalidation to refresh the CDN caches
          - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $PROD_DISTRIBUTION_ID
    - step: &deploy-to-develop
        name: Deploy to develop
        deployment: Development
        trigger: automatic
        clone:
          enabled: false
        script:
          # sync your files to S3
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $CF_SITE_DEV_BUCKET
              LOCAL_PATH: 'build'
          # triggering a distribution invalidation to refresh the CDN caches
          - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DEV_DISTRIBUTION_ID

pipelines:
  branches:
    master:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step: *deploy-to-production
    
    develop:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            - npm run develop
            - npm test -- --watchAll=false
          artifacts:
            - build/**
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step: *deploy-to-develop
